name: Publish Release
on:
  push:
    tags:
      - v1.[0-9]+.[0-9]+
jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Zip artifacts with Gradle Wrapper
        run: ./gradlew clean build zipArtifacts
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
      - name: Get Version
        id: get_version
        shell: bash
        run: |
          version=$(sed -n 's/version=\(.*\)/\1/p' gradle.properties)
          echo "Version is $version"
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Upload Artifact
        run: |
          curl -X POST \
               --verbose \
               --form bundle=@build/outputs/dynamodb-client-test-starter-${{ steps.get_version.outputs.version }}.zip \
               -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
               "https://central.sonatype.com/api/v1/publisher/upload"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
  create-github-release:
    name: Create GitHub Release
    permissions:
      contents: write
    needs:
      - publish-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}